# Generated by Django 6.0.1 on 2026-01-07 18:24

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("icon", models.CharField(default="trophy", max_length=50)),
                ("xp_reward", models.IntegerField(default=50)),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("STREAK", "Streak Reach"),
                            ("TOTAL_COMPLETIONS", "Total Completions"),
                            ("LEVEL", "Level Reach"),
                            ("HABIT_COUNT", "Habit Count Created"),
                        ],
                        max_length=50,
                    ),
                ),
                ("threshold", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("EASY", "Easy (1x XP)"),
                            ("MEDIUM", "Medium (1.5x XP)"),
                            ("HARD", "Hard (2x XP)"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("category", models.CharField(default="General", max_length=50)),
                (
                    "frequency",
                    models.CharField(
                        choices=[("DAILY", "Daily"), ("WEEKLY", "Weekly")],
                        default="DAILY",
                        max_length=10,
                    ),
                ),
                ("current_streak", models.IntegerField(default=0)),
                ("longest_streak", models.IntegerField(default=0)),
                ("last_completed_date", models.DateField(blank=True, null=True)),
                ("reminder_time", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateField(default=datetime.date.today)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("xp", models.IntegerField(default=0)),
                ("level", models.IntegerField(default=1)),
                ("freeze_tokens", models.IntegerField(default=0)),
                ("avatar_url", models.CharField(blank=True, max_length=255, null=True)),
                ("total_habits_completed", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Occurence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                ("notes", models.TextField(blank=True, null=True)),
                ("mood", models.CharField(blank=True, max_length=20, null=True)),
                ("xp_gained", models.IntegerField(default=0)),
                ("token_earned", models.BooleanField(default=False)),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lifetrack.habit",
                    ),
                ),
            ],
            options={
                "unique_together": {("habit", "date")},
            },
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_earned", models.DateField(default=datetime.date.today)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lifetrack.achievement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "achievement")},
            },
        ),
    ]
